django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordResetView
from django_app.views import main, health_check
from user.views import profile, register, password
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='main'),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('my_farm/', include("my_farm.urls")),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('profile/', profile, name='profile'),
    path('profile/password_change/', password, name='password_change'),
    path('api/health/', health_check, name='health_check'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_farm/urls.py
from django.urls import path
from .views import home, group_data
from .views_herd import herd_list, add_herd, herd_detail, cattle_list_by_herd, search_herd, update_herd, \
    upload_herd_picture
from .views_movement_report import GenerateReportView, LivestockMovementReportView
from .views_field import field_list, field_detail, herd_list_by_field, update_field, add_field, upload_field_picture, \
    search_field
from .views_cattle import cattle_info, add_cattle, update_cattle, search_cattle, cattle_detail, \
    delete_confirmation_page, CattleDeleteView, upload_cattle_picture


app_name = "my_farm"

urlpatterns = [

    path('', home, name='home'),
    path('group_data/<slug:group_name>/', group_data, name='group_data'),

    path('generate_report/', GenerateReportView.as_view(), name='generate_report'),
    path('livestock_movement_report/', LivestockMovementReportView.as_view(), name='report'),

    path('cattle_info/', cattle_info, name='cattle_info'),
    path('cattle/<int:cattle_id>/', cattle_detail, name='cattle_detail'),
    path('add_cattle/', add_cattle, name='add_cattle'),
    path('update_cattle/<int:cattle_id>/', update_cattle, name='update_cattle'),
    path('upload_cattle_picture/<int:cattle_id>/', upload_cattle_picture, name='upload_cattle_picture'),
    path('cattle/delete/<int:pk>/', CattleDeleteView.as_view(), name='delete_cattle'),
    path('confirmation_page/', delete_confirmation_page, name='delete_confirmation_page'),
    path('search_cattle/', search_cattle, name='search_cattle'),

    path('herds/', herd_list, name='herd_list'),
    path('herds/<int:herd_id>/', herd_detail, name='herd_detail'),
    path('herds/new_herd', add_herd, name='add_herd'),
    path('herd/<int:herd_id>/cattle/', cattle_list_by_herd, name='cattle_list_by_herd'),
    path('herd/update_herd/<int:herd_id>/', update_herd, name='update_herd'),
    path('herd/upload_herd_picture/<int:herd_id>/', upload_herd_picture, name='upload_herd_picture'),
    path('search_herd/', search_herd, name='search_herd'),

    path('fields/', field_list, name='field_list'),
    path('fields/<int:field_id>/', field_detail, name='field_detail'),
    path('fields/new_field', add_field, name='add_field'),
    path('fields/<int:field_id>/herd/', herd_list_by_field, name='herd_list_by_field'),
    path('fields/update_field/<int:field_id>/', update_field, name='update_field'),
    path('fields/upload_field_picture/<int:field_id>/', upload_field_picture, name='upload_field_picture'),
    path('fields/search_field/', search_field, name='search_field')


]

my_farm/models.py
from django.db import models


class BaseModel(models.Model):
    """
    A base abstract model that provides a default manager and serves as a template for other models.
    """
    objects = models.Manager()

    class Meta:
        abstract = True


class CattleManager(models.Manager):
    """
    Custom manager for the Cattle model that filters out deleted cattle objects from the queryset.
    """

    def get_queryset(self):
        """
        Get the queryset for cattle objects with the 'deleted' field set to False.

        :return: A queryset containing cattle objects with 'deleted' set to False.
        """
        return super().get_queryset().filter(deleted=False)


class Cattle(models.Model):
    """
    Represents information about cattle, including breed, gender, acquisition method, and loss method.
    """

    BREED = [
        ('Angus', 'Angus'),
        ('Crossbreed', 'Crossbreed'),
    ]

    GENDER = [
        ('Heifer', 'Heifer'),
        ('Bull', 'Bull'),
        ('Cow', 'Cow'),
    ]

    ACQUISITION_METHOD = [
        ('Birth', 'Birth'),
        ('Purchase', 'Purchase'),
        ('Gift', 'Gift'),
    ]

    LOSS_METHOD = [
        ('Death', 'Death'),
        ('Sold', 'Sold'),
        ('Consumed', 'Consumed'),
        ('Gifted', 'Gifted'),
    ]

    type = models.CharField(default='Cattle', max_length=80, blank=False)
    number = models.CharField(max_length=80, blank=False, unique=True)
    name = models.CharField(max_length=80, blank=True, null=True)
    gender = models.CharField(choices=GENDER, max_length=80, blank=False)
    breed = models.CharField(choices=BREED, max_length=80, blank=False)
    birth_date = models.DateField(blank=True, null=True)
    acquisition_method = models.CharField(choices=ACQUISITION_METHOD, max_length=80, blank=True, null=True)
    entry_date = models.DateField(blank=True, null=True)
    herd = models.ForeignKey('Herd', on_delete=models.SET_NULL, blank=True, null=True)
    loss_method = models.CharField(choices=LOSS_METHOD, max_length=80, blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    comments = models.TextField(max_length=2000)
    deleted = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='cattle_pictures', blank=True, null=True)

    def delete(self):
        """
        Soft delete the cattle by setting the 'deleted' field to True and saving the object.
        """
        self.deleted = True
        self.save()

    class Meta:
        """
        Meta information for the Cattle model, including the human-readable names and default ordering.
        """
        verbose_name = "Cattle Info"
        verbose_name_plural = "Cattle Info"
        ordering = ['name']

    def __str__(self):
        """
        Returns a string representation of the cattle object, showing its name, gender, and birthdate.
        """
        return f'{self.name},  {self.gender}, {self.birth_date}'


class Field(models.Model):
    """
    Represents information about a field, including its name, location, and size.
    """
    SIZE_CHOICES = [
            ('ha', 'Ha'),
            ('ac', 'Ac'),
        ]

    name = models.CharField(max_length=80, blank=False)
    location = models.CharField(max_length=100, blank=False)
    coordinates = models.CharField(max_length=100, blank=False)
    field_size = models.FloatField(blank=True, null=True)
    size_unit = models.CharField(choices=SIZE_CHOICES, max_length=2, blank=True)
    field_type = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    description = models.TextField(max_length=1200, blank=True)
    picture = models.ImageField(upload_to='field_pictures', blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the field object, showing its name.
        """
        return self.name


class Herd(models.Model):
    """
    Represents information about a herd, including its name, location, and start date.
    """
    name = models.CharField(max_length=80, blank=False)
    location = models.CharField(max_length=100, blank=False)
    field = models.ForeignKey('Field', on_delete=models.SET_NULL, blank=True, null=True, related_name='field_herds')
    description = models.TextField(max_length=2000, blank=True)
    start_date = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    herd_leader = models.ForeignKey('Cattle', on_delete=models.SET_NULL, blank=True, null=True,
                                    related_name='herd_leader')
    picture = models.ImageField(upload_to='herd_pictures', blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the herd object, showing its name.
        """
        return self.name

my_farm/views.py
from datetime import date
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils import timezone
from .models import Herd, Field
from django.urls import reverse
from .cattle_groups import GroupsManagement, CattleGroupData


@login_required
def home(request):
    """
    Renders the home page of the "My Farm" application.

    Retrieves various statistics and groups of cattle for display on the home page.

    :param request: The HTTP request object.
    :return: The rendered home page with the required data.
    """
    active_herds_count = Herd.objects.filter(is_active=True, start_date__lte=timezone.now()).count()
    active_field_count = Field.objects.filter(is_active=True).count()

    groups_manager = GroupsManagement()
    today_groups = groups_manager.calculate_groups(estimation_date=date.today())

    total_cattle_count = 0
    for group_data in today_groups.values():
        alive_cows_in_group = 0
        for cattle_data in group_data:
            if cattle_data['cattle']['end_date'] is None:
                alive_cows_in_group += 1
        total_cattle_count += alive_cows_in_group

    groups = []
    for group_name, cattle_data in today_groups.items():
        group = CattleGroupData(group_name, cattle_data)
        group.count_active_cattle()
        group_url = reverse('my_farm:group_data', args=[slugify(group_name)])
        group.url = group_url
        groups.append(group)

    context = {
        'groups': groups,
        'active_herds_count': active_herds_count,
        'active_field_count': active_field_count,
        'total_cattle_count': total_cattle_count,
    }

    return render(request, 'my_farm/my_farm_main.html', context)


def group_data(request, group_name):
    """
    Renders the group data page for the selected group.

    Retrieves the cattle data for the selected group and displays it on the page.

    :param request: The HTTP request object.
    :param group_name: The name of the selected group.
    :return: The rendered group data page with the selected group's data.
    """
    groups_manager = GroupsManagement()
    today_cattle = groups_manager.calculate_groups(estimation_date=date.today())

    selected_group = group_name

    groups = []
    if selected_group in today_cattle:
        cattle_data = today_cattle[selected_group]
        group = CattleGroupData(selected_group, cattle_data)
        group.cattle_data()
        groups.append(group)

    context = {
        'groups': groups,
        'selected_group': selected_group
    }
    return render(request, 'my_farm/group_data.html', context)

my_farm/templates/my_farm/generate_report.html
{% extends 'base_user.html' %}

{% block content %}
<head>
  <title>Generate Report</title>
</head>

<body>
  <h3 class="text-uppercase" style="text-align: center; margin: 30px;">Generate report</h3>

  <div class="card-report">
    <div class="report-container-report">
      <form method="post" action="{% url 'my_farm:generate_report' %}">
        {% csrf_token %}
        <div class="date-inputs-report">
          <div class="form-group">
            <label for="start_date">Start Date:</label>
            <input type="date" id="start_date" name="start_date" required>
          </div>

          <div class="form-group">
            <label for="end_date">End Date:</label>
            <input type="date" id="end_date" name="end_date" required>
          </div>
        </div>

        <button type="submit" class="btn btn-custom">Generate Report</button>
      </form>
    </div>
  </div>
</body>

{% endblock %}

my_farm/templates/my_farm/group_data.html
{% extends 'base_user.html' %}

{% block content %}
  <title>Group Data</title>

  <h3 class="text-uppercase" style="text-align: center; margin: 30px;">Group Data - {{ selected_group }}</h3>

  <div class="table-responsive">
    <table id="group-data-table" class="table table-bordered">
      <thead>
        <tr class="column-names-groups">
          <th>Type</th>
          <th>Number</th>
          <th>Name</th>
          <th>Gender</th>
          <th>Breed</th>
          <th>Birth Date</th>
          <th>Acquisition Method</th>
          <th>Entry Date</th>
          <th class="comments">Comments</th>
        </tr>
      </thead>
<tbody>
  {% for group in groups %}
    {% for cattle in group.cattle_list %}
      <tr>
        <td>{{ cattle.type }}</td>
        <td class="cattle-number">
          <a href="{% url 'my_farm:cattle_detail' cattle.id %}">{{ cattle.number }}</a>
        </td>
        <td>{{ cattle.name }}</td>
        <td>{{ cattle.gender }}</td>
        <td>{{ cattle.breed }}</td>
        <td>{{ cattle.birth_date|date:"Y-m-d" }}</td>
        <td>{{ cattle.acquisition_method }}</td>
        <td>{{ cattle.entry_date|date:"Y-m-d" }}</td>
        <td>
          <div id="comments-short-{{ cattle.id }}">{{ cattle.comments|truncatechars:20 }}</div>
          <div id="comments-full-{{ cattle.id }}" style="display: none;">{{ cattle.comments }}</div>
          <small>
            <a href="#" data-cattle-id="{{ cattle.id }}" data-action="toggle-comments" onclick="toggleComments({{ cattle.id }}); return false;" style="display: inline;">Show More</a>
          </small>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="9">No cattle in the group.</td>
      </tr>
    {% endfor %}
  {% endfor %}
</tbody>
    </table>
  </div>

{% block scripts %}
  <script>
    function toggleComments(cattleId) {
      const shortComments = document.querySelector(`#comments-short-${cattleId}`);
      const fullComments = document.querySelector(`#comments-full-${cattleId}`);
      const toggleLink = document.querySelector(`a[data-cattle-id="${cattleId}"][data-action="toggle-comments"]`);

      if (shortComments.style.display === "none") {
        // Show short comments and hide full comments
        shortComments.style.display = "";
        fullComments.style.display = "none";
        toggleLink.textContent = "Show More";
      } else {
        // Show full comments and hide short comments
        shortComments.style.display = "none";
        fullComments.style.display = "";
        toggleLink.textContent = "Show Less";
      }
    }
  </script>
{% endblock %}

{% endblock %}

my_farm/templates/my_farm/livestock_movement_report.html
{% extends 'base_user.html' %}
{% block content %}



  <div class="report-info">
    <p>Reporting Start Date: {{ start_date }}</p>
    <p>Reporting End Date: {{ end_date }}</p>
  </div>

  <div class="table-responsive">
    <div class="table-container">
      <table class="table table-bordered">
        <thead>
          <tr class="column-names">
            <th rowspan="3">Group Name</th>
            <th class="border-column" colspan="2" rowspan="2">Beginning of period</th>
            <th class="border-column" colspan="2" rowspan="2">Births</th>
            <th class="border-column" colspan="2" rowspan="2">Purchases</th>
            <th class="border-column" colspan="2" rowspan="2">Gifts</th>
            <th colspan="4">Movement between groups</th>
            <th colspan="2" rowspan="2">Deaths</th>
            <th colspan="2" rowspan="2">Sold</th>
            <th colspan="2" rowspan="2">Consumed</th>
            <th colspan="2" rowspan="2">Gifted</th>
            <th colspan="2" rowspan="2">End of period</th>
            <th colspan="2" rowspan="2">Difference</th>
          </tr>
          <tr>
            <th colspan="2">To</th>
            <th colspan="2">From</th>
          </tr>
          <tr>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
            <th>pcs</th>
            <th>kg</th>
          </tr>
        </thead>
        <tbody>
          {% for group in groups %}
            <tr>
              <td>{{ group.group_name }}</td>
              <td class="beginning-pcs-cell">{% if group.start_date_count == 0 %}{% else %}{{ group.start_date_count }}{% endif %}</td>
              <td class="beginning-kg-cell">{% if group.start_date_group_weight == 0 %}{% else %}{{ group.start_date_group_weight }}{% endif %}</td>
              <td>{% if group.birth_count == 0 %}{% else %}{{ group.birth_count }}{% endif %}</td>
              <td>{% if group.birth_weight == 0 %}{% else %}{{ group.birth_weight }}{% endif %}</td>
              <td>{% if group.purchase_count == 0 %}{% else %}{{ group.purchase_count }}{% endif %}</td>
              <td>{% if group.purchase_weight == 0 %}{% else %}{{ group.purchase_weight }}{% endif %}</td>
              <td>{% if group.gift_count == 0 %}{% else %}{{ group.gift_count }}{% endif %}</td>
              <td>{% if group.gift_weight == 0 %}{% else %}{{ group.gift_weight }}{% endif %}</td>
              <td>{% if group.moved_in == 0 %}{% else %}{{ group.moved_in }}{% endif %}</td>
              <td>{% if group.weight_moved_in == 0 %}{% else %}{{ group.weight_moved_in }}{% endif %}</td>
              <td>{% if group.moved_out == 0 %}{% else %}{{ group.moved_out }}{% endif %}</td>
              <td>{% if group.weight_moved_out == 0 %}{% else %}{{ group.weight_moved_out }}{% endif %}</td>
              <td>{% if group.death_count == 0 %}{% else %}{{ group.death_count }}{% endif %}</td>
              <td>{% if group.death_weight == 0 %}{% else %}{{ group.death_weight }}{% endif %}</td>
              <td>{% if group.sold_count == 0 %}{% else %}{{ group.sold_count }}{% endif %}</td>
              <td>{% if group.sold_weight == 0 %}{% else %}{{ group.sold_weight }}{% endif %}</td>
              <td>{% if group.consumed_count == 0 %}{% else %}{{ group.consumed_count }}{% endif %}</td>
              <td>{% if group.consumed_weight == 0 %}{% else %}{{ group.consumed_weight }}{% endif %}</td>
              <td>{% if group.gifted_count == 0 %}{% else %}{{ group.gifted_count }}{% endif %}</td>
              <td>{% if group.gifted_weight == 0 %}{% else %}{{ group.gifted_weight }}{% endif %}</td>
              <td class="end-pcs-cell">{% if group.end_date_count == 0 %}{% else %}{{ group.end_date_count }}{% endif %}</td>
              <td class="end-kg-cell">{% if group.end_date_group_weight == 0 %}{% else %}{{ group.end_date_group_weight }}{% endif %}</td>
              <td>{% if group.count_difference == 0 %}{% else %}{{ group.count_difference }}{% endif %}</td>
              <td>{% if group.weight_difference == 0 %}{% else %}{{ group.weight_difference }}{% endif %}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}

my_farm/templates/my_farm/my_farm_main.html
{% extends 'base_user.html' %}

{% block content %}
  {% load static %}

<div class="container-fluid mt-3 mb-3">
  <section id="summary">
    <div class="row">
      <div class="col-12 mt-3 mb-1">
        <h4 class="text-uppercase">Your farm summary</h4>
        <div style="height: 20px;"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-3 col-sm-6 col-12">
        <a href="{% url 'my_farm:cattle_info' %}?query_loss_method_null=True">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="align-self-center">
                    <img src="{% static 'img/cattle.png' %}" width="60" height="60" alt="Cattle Icon">
                  </div>
                  <div class="media-body text-center">
                    <h3>{{ total_cattle_count }}</h3>
                    <span>Current Livestock </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>

      <div class="col-xl-3 col-sm-6 col-12">
        <a href="{% url 'my_farm:group_data' group_name='Cows' %}">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="align-self-center">
                    <img src="{% static 'img/cow3.png' %}" width="60" height="60" alt="Cow Icon">
                  </div>
                  <div class="media-body text-center">
                      {% for group in groups %}
                        {% if group.group_name == 'Cows' %}
                          <h3>{{ group.active_cattle }}</h3>
                          <span>Cows</span>
                        {% endif %}
                      {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>

      <div class="col-xl-3 col-sm-6 col-12">
         <a href="{% url 'my_farm:group_data' group_name='Calves' %}">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="align-self-center">
                    <img src="{% static 'img/calve1.png' %}" width="60" height="60" alt="Calve Icon">
                  </div>
                  <div class="media-body text-center">
                      {% for group in groups %}
                        {% if group.group_name == 'Calves' %}
                          <h3>{{ group.active_cattle }}</h3>
                          <span>Calves</span>
                        {% endif %}
                      {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>

      <div class="col-xl-3 col-sm-6 col-12">
        <a href="{% url 'my_farm:group_data' group_name='Young_Heifer' %}">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="align-self-center">
                    <img src="{% static 'img/youngcow.png' %}" width="60" height="60" alt="Young Heifer Icon">
                  </div>
                  <div class="media-body text-center">
                    {% for group in groups %}
                        {% if group.group_name == 'Young_Heifer' %}
                    <h3>{{ group.active_cattle }}</h3>
                    <span>Young Heifers</span>
                    {% endif %}
                      {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-3 col-sm-6 col-12">
        <a href="{% url 'my_farm:group_data' group_name='Adult_Heifer' %}">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="media-body text-left">
                    {% for group in groups %}
                        {% if group.group_name == 'Adult_Heifer' %}
                    <h3>{{ group.active_cattle }}</h3>
                    <span>Adult Heifers</span>
                    {% endif %}
                      {% endfor %}
                  </div>
                  <div class="align-self-center">
                    <img src="{% static 'img/cowcow.png' %}" width="60" height="60">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>

      <div class="col-xl-3 col-sm-6 col-12">
        <a href="{% url 'my_farm:group_data' group_name='Young_Bull' %}">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="media-body text-left">
                    {% for group in groups %}
                        {% if group.group_name == 'Young_Bull' %}
                    <h3>{{ group.active_cattle }}</h3>
                    <span>Young Bulls</span>
                    {% endif %}
                      {% endfor %}
                  </div>
                  <div class="align-self-center">
                    <img src="{% static 'img/youngbull.png' %}" width="60" height="60" alt="Young Bull Icon">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>

      <div class="col-xl-3 col-sm-6 col-12">
        <a href="{% url 'my_farm:group_data' group_name='Adult_Bull' %}">
          <div class="card mb-3">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="media-body text-left">
                    {% for group in groups %}
                        {% if group.group_name == 'Adult_Bull' %}
                    <h3>{{ group.active_cattle }}</h3>
                    <span>Adult Bulls</span>
                    {% endif %}
                      {% endfor %}
                  </div>
                  <div class="align-self-center">
                    <img src="{% static 'img/adultbull.png' %}" width="60" height="60" alt="Adult Bull Icon">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>

      <div class="col-xl-3 col-sm-6 col-12">
        <a style="background-color: #fcecc0;" href="{% url 'my_farm:herd_list' %}?is_active=True">
          <div class="card mb-3" style="background-color: #fcecc0;">
            <div class="card-content">
              <div class="card-body">
                <div class="media d-flex">
                  <div class="media-body text-left">
                    <h4 class="primary">{{ active_herds_count }}</h4>
                    <span>Active Herds</span>
                  </div>
                  <div class="align-self-center">
                    <img src="{% static 'img/herd.png' %}" width="60" height="60" alt="Active Herds Icon">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

<div class="row" style="display: flex;">
  <div class="col-xl-9 col-sm-6 col-12">
    <div class="card mb-3" style="flex: 1; height: 80%;">
      <div class="card-content">
        <div class="card-body">
          <div class="media d-flex">
<div class="text-center">
  <a href="{% url 'my_farm:generate_report' %}" class="d-inline-block" style="font-size: 20px;">
    Livestock movement report
  </a>
</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xl-3 col-sm-6 col-12">
    <a href="{% url 'my_farm:field_list' %}?is_active=True">
      <div class="card mb-3" style="background-color: #e1f2e6; height: 80%;">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
             <div class="align-self-center">
                <img src="{% static 'img/fields.png' %}" width="60" height="60">
              </div>
              <div class="media-body text-center">
                <h3 class="primary">{{ active_field_count }}</h3>
                <span>Active Fields</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>




  </section>
</div>

{% endblock %}

my_farm/templates/my_farm/update_cattle.html
{% extends 'base_user.html' %}
{% block content %}
{% load static %}
<head>
  <title>Update Cattle Information</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="{% static 'css/form_styles.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>
<body>
  <h3 style="text-align: center; margin: 20px;">Update {{ cattle.name }} information</h3>
  <div class="card">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.number.id_for_label }}">Number:</label>
        {{ form.number }}
      </div>
      <div class="form-group">
        <label for="{{ form.name.id_for_label }}">Name:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label for="{{ form.gender.id_for_label }}">Gender:</label>
        {{ form.gender }}
      </div>
      <div class="form-group">
        <label for="{{ form.breed.id_for_label }}">Breed:</label>
        {{ form.breed }}
      </div>
      <div class="form-group">
        <label for="{{ form.birth_date.id_for_label }}">Birth Date:</label>
        {{ form.birth_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.acquisition_method.id_for_label }}">Acquisition Method:</label>
        {{ form.acquisition_method }}
      </div>
      <div class="form-group">
        <label for="{{ form.entry_date.id_for_label }}">Entry Date:</label>
        {{ form.entry_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.loss_method.id_for_label }}">Loss Method:</label>
        {{ form.loss_method }}
      </div>
      <div class="form-group">
        <label for="{{ form.end_date.id_for_label }}">End Date:</label>
        {{ form.end_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.comments.id_for_label }}">Comments:</label>
        {{ form.comments }}
      </div>
      <div class="form-group">
        <label for="{{ form.picture.id_for_label }}">Picture:</label>
        {{ form.picture }}
      </div>
      <button type="submit" class="btn btn-custom">Save</button>
    </form>
  </div>
  <script>
    flatpickr("#id_birth_date, #id_entry_date, #id_end_date", {
      dateFormat: "Y-m-d",
    });
  </script>
</body>
{% endblock %}

my_farm/templates/my_farm/upload_picture.html
{% extends 'base_user.html' %}

{% block content %}
<div class="card" style="max-width: 400px; margin: 20px auto; padding: 20px;">
    <h3 style="text-align: left; margin-top: 20px;">Upload Picture</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="btn btn-danger">
            <input type="file" name="picture" accept="image/*" style="display: none;">
            Choose File
        </label>
        <div style="height: 20px;"></div>
        <button class="btn btn-custom" type="submit">Upload</button>
    </form>
</div>
{% endblock %}