django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordResetView
from django_app.views import main, health_check
from user.views import profile, register, password
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='main'),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('my_farm/', include("my_farm.urls")),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('profile/', profile, name='profile'),
    path('profile/password_change/', password, name='password_change'),
    path('api/health/', health_check, name='health_check'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_farm/urls.py
from django.urls import path
from .views import home, group_data
from .views_herd import herd_list, add_herd, herd_detail, cattle_list_by_herd, search_herd, update_herd, \
    upload_herd_picture
from .views_movement_report import GenerateReportView, LivestockMovementReportView
from .views_field import field_list, field_detail, herd_list_by_field, update_field, add_field, upload_field_picture, \
    search_field
from .views_cattle import cattle_info, add_cattle, update_cattle, search_cattle, cattle_detail, \
    delete_confirmation_page, CattleDeleteView, upload_cattle_picture


app_name = "my_farm"

urlpatterns = [

    path('', home, name='home'),
    path('group_data/<slug:group_name>/', group_data, name='group_data'),

    path('generate_report/', GenerateReportView.as_view(), name='generate_report'),
    path('livestock_movement_report/', LivestockMovementReportView.as_view(), name='report'),

    path('cattle_info/', cattle_info, name='cattle_info'),
    path('cattle/<int:cattle_id>/', cattle_detail, name='cattle_detail'),
    path('add_cattle/', add_cattle, name='add_cattle'),
    path('update_cattle/<int:cattle_id>/', update_cattle, name='update_cattle'),
    path('upload_cattle_picture/<int:cattle_id>/', upload_cattle_picture, name='upload_cattle_picture'),
    path('cattle/delete/<int:pk>/', CattleDeleteView.as_view(), name='delete_cattle'),
    path('confirmation_page/', delete_confirmation_page, name='delete_confirmation_page'),
    path('search_cattle/', search_cattle, name='search_cattle'),

    path('herds/', herd_list, name='herd_list'),
    path('herds/<int:herd_id>/', herd_detail, name='herd_detail'),
    path('herds/new_herd', add_herd, name='add_herd'),
    path('herd/<int:herd_id>/cattle/', cattle_list_by_herd, name='cattle_list_by_herd'),
    path('herd/update_herd/<int:herd_id>/', update_herd, name='update_herd'),
    path('herd/upload_herd_picture/<int:herd_id>/', upload_herd_picture, name='upload_herd_picture'),
    path('search_herd/', search_herd, name='search_herd'),

    path('fields/', field_list, name='field_list'),
    path('fields/<int:field_id>/', field_detail, name='field_detail'),
    path('fields/new_field', add_field, name='add_field'),
    path('fields/<int:field_id>/herd/', herd_list_by_field, name='herd_list_by_field'),
    path('fields/update_field/<int:field_id>/', update_field, name='update_field'),
    path('fields/upload_field_picture/<int:field_id>/', upload_field_picture, name='upload_field_picture'),
    path('fields/search_field/', search_field, name='search_field')


]

my_farm/models.py
from django.db import models


class BaseModel(models.Model):
    """
    A base abstract model that provides a default manager and serves as a template for other models.
    """
    objects = models.Manager()

    class Meta:
        abstract = True


class CattleManager(models.Manager):
    """
    Custom manager for the Cattle model that filters out deleted cattle objects from the queryset.
    """

    def get_queryset(self):
        """
        Get the queryset for cattle objects with the 'deleted' field set to False.

        :return: A queryset containing cattle objects with 'deleted' set to False.
        """
        return super().get_queryset().filter(deleted=False)


class Cattle(models.Model):
    """
    Represents information about cattle, including breed, gender, acquisition method, and loss method.
    """

    BREED = [
        ('Angus', 'Angus'),
        ('Crossbreed', 'Crossbreed'),
    ]

    GENDER = [
        ('Heifer', 'Heifer'),
        ('Bull', 'Bull'),
        ('Cow', 'Cow'),
    ]

    ACQUISITION_METHOD = [
        ('Birth', 'Birth'),
        ('Purchase', 'Purchase'),
        ('Gift', 'Gift'),
    ]

    LOSS_METHOD = [
        ('Death', 'Death'),
        ('Sold', 'Sold'),
        ('Consumed', 'Consumed'),
        ('Gifted', 'Gifted'),
    ]

    type = models.CharField(default='Cattle', max_length=80, blank=False)
    number = models.CharField(max_length=80, blank=False, unique=True)
    name = models.CharField(max_length=80, blank=True, null=True)
    gender = models.CharField(choices=GENDER, max_length=80, blank=False)
    breed = models.CharField(choices=BREED, max_length=80, blank=False)
    birth_date = models.DateField(blank=True, null=True)
    acquisition_method = models.CharField(choices=ACQUISITION_METHOD, max_length=80, blank=True, null=True)
    entry_date = models.DateField(blank=True, null=True)
    herd = models.ForeignKey('Herd', on_delete=models.SET_NULL, blank=True, null=True)
    loss_method = models.CharField(choices=LOSS_METHOD, max_length=80, blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    comments = models.TextField(max_length=2000)
    deleted = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='cattle_pictures', blank=True, null=True)

    def delete(self):
        """
        Soft delete the cattle by setting the 'deleted' field to True and saving the object.
        """
        self.deleted = True
        self.save()

    class Meta:
        """
        Meta information for the Cattle model, including the human-readable names and default ordering.
        """
        verbose_name = "Cattle Info"
        verbose_name_plural = "Cattle Info"
        ordering = ['name']

    def __str__(self):
        """
        Returns a string representation of the cattle object, showing its name, gender, and birthdate.
        """
        return f'{self.name},  {self.gender}, {self.birth_date}'


class Field(models.Model):
    """
    Represents information about a field, including its name, location, and size.
    """
    SIZE_CHOICES = [
            ('ha', 'Ha'),
            ('ac', 'Ac'),
        ]

    name = models.CharField(max_length=80, blank=False)
    location = models.CharField(max_length=100, blank=False)
    coordinates = models.CharField(max_length=100, blank=False)
    field_size = models.FloatField(blank=True, null=True)
    size_unit = models.CharField(choices=SIZE_CHOICES, max_length=2, blank=True)
    field_type = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    description = models.TextField(max_length=1200, blank=True)
    picture = models.ImageField(upload_to='field_pictures', blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the field object, showing its name.
        """
        return self.name


class Herd(models.Model):
    """
    Represents information about a herd, including its name, location, and start date.
    """
    name = models.CharField(max_length=80, blank=False)
    location = models.CharField(max_length=100, blank=False)
    field = models.ForeignKey('Field', on_delete=models.SET_NULL, blank=True, null=True, related_name='field_herds')
    description = models.TextField(max_length=2000, blank=True)
    start_date = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    herd_leader = models.ForeignKey('Cattle', on_delete=models.SET_NULL, blank=True, null=True,
                                    related_name='herd_leader')
    picture = models.ImageField(upload_to='herd_pictures', blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the herd object, showing its name.
        """
        return self.name

my_farm/views.py
from datetime import date
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils import timezone
from .models import Herd, Field
from django.urls import reverse
from .cattle_groups import GroupsManagement, CattleGroupData


@login_required
def home(request):
    """
    Renders the home page of the "My Farm" application.

    Retrieves various statistics and groups of cattle for display on the home page.

    :param request: The HTTP request object.
    :return: The rendered home page with the required data.
    """
    active_herds_count = Herd.objects.filter(is_active=True, start_date__lte=timezone.now()).count()
    active_field_count = Field.objects.filter(is_active=True).count()

    groups_manager = GroupsManagement()
    today_groups = groups_manager.calculate_groups(estimation_date=date.today())

    total_cattle_count = 0
    for group_data in today_groups.values():
        alive_cows_in_group = 0
        for cattle_data in group_data:
            if cattle_data['cattle']['end_date'] is None:
                alive_cows_in_group += 1
        total_cattle_count += alive_cows_in_group

    groups = []
    for group_name, cattle_data in today_groups.items():
        group = CattleGroupData(group_name, cattle_data)
        group.count_active_cattle()
        group_url = reverse('my_farm:group_data', args=[slugify(group_name)])
        group.url = group_url
        groups.append(group)

    context = {
        'groups': groups,
        'active_herds_count': active_herds_count,
        'active_field_count': active_field_count,
        'total_cattle_count': total_cattle_count,
    }

    return render(request, 'my_farm/my_farm_main.html', context)


def group_data(request, group_name):
    """
    Renders the group data page for the selected group.

    Retrieves the cattle data for the selected group and displays it on the page.

    :param request: The HTTP request object.
    :param group_name: The name of the selected group.
    :return: The rendered group data page with the selected group's data.
    """
    groups_manager = GroupsManagement()
    today_cattle = groups_manager.calculate_groups(estimation_date=date.today())

    selected_group = group_name

    groups = []
    if selected_group in today_cattle:
        cattle_data = today_cattle[selected_group]
        group = CattleGroupData(selected_group, cattle_data)
        group.cattle_data()
        groups.append(group)

    context = {
        'groups': groups,
        'selected_group': selected_group
    }
    return render(request, 'my_farm/group_data.html', context)

my_farm/templates/cattle/add_cattle.html
{% extends 'base_user.html' %}

{% block content %}
<head>
  <title>Add Cattle</title>

</head>

<body>
  <h3 class="text-uppercase" style="text-align: center; margin: 20px;">Add Cattle</h3>
  <div class="card-cattle">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.number.id_for_label }}" class="label-cattle">Number:</label>
        {{ form.number }}
      </div>
      <div class="form-group">
        <label for="{{ form.name.id_for_label }}" class="label-cattle">Name:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label for="{{ form.gender.id_for_label }}" class="label-cattle">Gender:</label>
        {{ form.gender }}
      </div>
      <div class="form-group">
        <label for="{{ form.breed.id_for_label }}" class="label-cattle">Breed:</label>
        {{ form.breed }}
      </div>
      <div class="form-group">
        <label for="{{ form.birth_date.id_for_label }}" class="label-cattle">Birth Date:</label>
        {{ form.birth_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.acquisition_method.id_for_label }}" class="label-cattle">Acquisition Method:</label>
        {{ form.acquisition_method }}
      </div>
      <div class="form-group">
        <label for="{{ form.entry_date.id_for_label }}" class="label-cattle">Entry Date:</label>
        {{ form.entry_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.loss_method.id_for_label }}" class="label-cattle">Loss Method:</label>
        {{ form.loss_method }}
      </div>
      <div class="form-group">
        <label for="{{ form.end_date.id_for_label }}" class="label-cattle">End Date:</label>
        {{ form.end_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.comments.id_for_label }}" class="label-cattle">Comments:</label>
        {{ form.comments }}
      </div>
      <div class="form-group">
        <label for="{{ form.picture.id_for_label }}" class="label-cattle">Picture:</label>
        {{ form.picture }}
      </div>
      <div class="form-group">
        <label for="id_herd" class="label-cattle">Herd:</label>
        <select class="form-control" id="id_herd" name="herd">
          {% for herd in herd_queryset %}
            <option value="{{ herd.id }}">{{ herd.name }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-custom">Add cattle information</button>
    </form>
  </div>

</body>

{% endblock %}

my_farm/templates/cattle/cattle_confirm_delete.html
{% extends 'base_user.html' %}

{% block content %}
  <div class="card" style="max-width: 400px; margin: 20px auto; padding: 20px;">
    <h3 style="text-align: left; margin-top: 20px;">Confirm Delete</h3>
    <p>Are you sure you want to delete this cattle?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'my_farm:cattle_info' %}" class="btn btn-secondary" style="margin-left: 10px;">Cancel</a>
    </form>
  </div>
{% endblock %}

my_farm/templates/cattle/cattle_detail.html
{% extends 'base_user.html' %}
{% block content %}


<title>Cattle Detail</title>


    {% if cattle %}
        <h4 style="text-align: center; margin: 20px; font-weight: bold;">Cattle {{ cattle.name }}</h4>

        <table class="table table-bordered" style="max-width: 500; margin-left: auto; margin-right: auto">
            <tr>
                <th class="cattle-detail">Picture</th>
                <td style="width: 300px; height: 200px; max-width: 100%; max-height: 100%;">
                    {% if cattle.picture %}
                        <img src="{{ cattle.picture.url }}" alt="Cattle Picture" style="max-width: 100%; max-height: 100%;">
                    {% else %}
                        No picture available.
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="cattle-detail"></th>
                <td>
                    <a href="{% url 'my_farm:upload_cattle_picture' cattle_id=cattle.id %}">Upload Picture</a>
                </td>
            </tr>
            <tr>
                <th class="cattle-detail">Type</th>
                <td>{{ cattle.type }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Number</th>
                <td>{{ cattle.number }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Name</th>
                <td>{{ cattle.name }}</td>
            </tr>
<tr>
    <th class="cattle-detail">Herd</th>
    <td>
         {% if cattle.herd %}
        <a href="{% url 'my_farm:herd_detail' cattle.herd.id %}">{{ cattle.herd }}</a>
         {% else %}
        No cattle.
                    {% endif %}
                </td>
</tr>
            <tr>
                <th class="cattle-detail">Gender</th>
                <td>{{ cattle.gender }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Breed</th>
                <td>{{ cattle.breed }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Birth Date</th>
                <td>{{ cattle.birth_date }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Acquisition Method</th>
                <td>{{ cattle.acquisition_method }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Entry Date</th>
                <td>{{ cattle.entry_date }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Loss Method</th>
                <td>{{ cattle.loss_method }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">End Date</th>
                <td>{{ cattle.end_date }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Comments</th>
                <td>{{ cattle.comments }}</td>
            </tr>
            <tr>
                <th class="cattle-detail">Update</th>
                <td>
                    <!-- Update link -->
                    <a href="{% url 'my_farm:update_cattle' cattle.id %}">Update</a>
                </td>
            </tr>
            <tr>
                <th class="cattle-detail">Delete</th>
                <td>
                    <!-- Delete link -->
                    <a href="{% url 'my_farm:delete_cattle' pk=cattle.id %}" onclick="return confirm('Are you sure you want to delete this cow?');">Delete</a>
                </td>
            </tr>
        </table>


    {% else %}
        <p>No cattle selected.</p>
    {% endif %}
{% endblock %}

my_farm/templates/cattle/cattle_info.html
{% extends 'base_user.html' %}
{% block content %}

<title>Cattle info</title>


<h3 class="text-uppercase" style="text-align: center; margin: 20px;">All Cattle</h3>

    <form method="POST" action="{% url 'my_farm:add_cattle' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-custom">Add cattle information</button>
    </form>

 <p></p>

    <!-- Search Tool -->
    <form method="GET" action="{% url 'my_farm:search_cattle' %}">
        <input type="text" name="query" placeholder="Search...">
        <button type="submit" >Search</button>
    </form>


<p>Select the columns you want to see:</p>
<form id="column-form">
    {% csrf_token %}
    <label for="id_type">Type</label>
    <input type="checkbox" name="columns" value="type" id="id_type" checked>
    <label for="id_number">Number</label>
    <input type="checkbox" name="columns" value="number" id="id_number" checked>
    <label for="id_name">Name</label>
    <input type="checkbox" name="columns" value="name" id="id_name" checked>
    <label for="id_gender">Gender</label>
    <input type="checkbox" name="columns" value="gender" id="id_gender" checked>
    <label for="id_breed">Breed</label>
    <input type="checkbox" name="columns" value="breed" id="id_breed" checked>
    <label for="id_birth_date">Birth Date</label>
    <input type="checkbox" name="columns" value="birth_date" id="id_birth_date" checked>
    <label for="id_acquisition_method">Acquisition method</label>
    <input type="checkbox" name="columns" value="acquisition_method" id="id_acquisition_method" checked>
    <label for="id_entry_date">Entry date</label>
    <input type="checkbox" name="columns" value="entry_date" id="id_entry_date" checked>
    <label for="id_loss_method">Loss method</label>
    <input type="checkbox" name="columns" value="loss_method" id="id_loss_method" checked>
    <label for="id_end_date">End date</label>
    <input type="checkbox" name="columns" value="end_date" id="id_end_date" checked>
    <label for="id_comments">Comments</label>
    <input type="checkbox" name="columns" value="comments" id="id_comments" checked>
    <button type="submit">Apply</button>
</form>

<div class="table-responsive">
<table id="cattle-table" class="table table-bordered">
  <thead>
    <tr class="column-names">
      <th class="cattle-type">Type</th>
      <th class="cattle-number">Number</th>
      <th class="cattle-name">Name</th>
      <th class="cattle-gender">Gender</th>
      <th class="cattle-breed">Breed</th>
      <th class="cattle-birth_date">Birth date</th>
      <th class="cattle-acquisition_method">Acquisition method</th>
      <th class="cattle-entry_date">Entry date</th>
      <th class="cattle-loss_method">Loss method</th>
      <th class="cattle-end_date">End date</th>
      <th class="cattle-comments">Comments</th>
    </tr>
  </thead>
  <tbody>
    {% for cow in cattle %}
    <tr>
      <td class="cattle-type">{{ cow.type }}</td>
      <td class="cattle-number">
        <a href="{% url 'my_farm:cattle_detail' cow.id %}">{{ cow.number }}</a>
      </td>
      <td class="cattle-name">{{ cow.name }}</td>
      <td class="cattle-gender">{{ cow.gender }}</td>
      <td class="cattle-breed">{{ cow.breed }}</td>
      <td class="cattle-birth_date">{{ cow.birth_date|date:"Y-m-d" }}</td>
      <td class="cattle-acquisition_method">{{ cow.acquisition_method }}</td>
      <td class="cattle-entry_date">{{ cow.entry_date|date:"Y-m-d" }}</td>
      <td class="cattle-loss_method">{{ cow.loss_method }}</td>
      <td class="cattle-end_date">{{ cow.end_date|date:"Y-m-d" }}</td>
      <td class="cattle-comments">
        <div id="comments-short-{{ cow.id }}">{{ cow.comments|truncatechars:20 }}</div>
        <div id="comments-full-{{ cow.id }}" style="display: none;">{{ cow.comments }}</div>
        <a href="#" data-cow-id="{{ cow.id }}" data-action="show-more" onclick="showFullComments({{ cow.id }}); return false;">Show More</a>
        <a href="#" data-cow-id="{{ cow.id }}" data-action="show-less" onclick="showShortComments({{ cow.id }}); return false;" style="display: none;">Show Less</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>

    {% if cattle.has_other_pages %}
        <div class="pagination justify-content-center">
            {% if cattle.has_previous %}
                <a href="?page=1" class="page-link">&laquo; First</a>
                <a href="?page={{ cattle.previous_page_number }}" class="page-link">&lsaquo; Previous</a>
            {% endif %}

            {% for num in cattle.paginator.page_range %}
                {% if cattle.number == num %}
                    <a href="?page={{ num }}" class="page-link active">{{ num }}</a>
                {% else %}
                    <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if cattle.has_next %}
                <a href="?page={{ cattle.next_page_number }}" class="page-link">Next &rsaquo;</a>
                <a href="?page={{ cattle.paginator.num_pages }}" class="page-link">Last &raquo;</a>
            {% endif %}
        </div>
    {% endif %}

{% block scripts %}
  <script>
     // Function to show the full comments when "Show More" is clicked
    function showFullComments(cowId) {
        const shortComments = document.querySelector(`#comments-short-${cowId}`);
        const fullComments = document.querySelector(`#comments-full-${cowId}`);
        const showMoreLink = document.querySelector(`a[data-cow-id="${cowId}"]`);
        const showLessLink = document.querySelector(`a[data-cow-id="${cowId}"][data-action="show-less"]`);

        // Hide the short comments and show the full comments
        shortComments.style.display = "none";
        fullComments.style.display = "";

        // Hide the "Show More" link and show the "Show Less" link
        showMoreLink.style.display = "none";
        showLessLink.style.display = "";
    }

    // Function to show the short comments when "Show Less" is clicked
    function showShortComments(cowId) {
        const shortComments = document.querySelector(`#comments-short-${cowId}`);
        const fullComments = document.querySelector(`#comments-full-${cowId}`);
        const showMoreLink = document.querySelector(`a[data-cow-id="${cowId}"]`);
        const showLessLink = document.querySelector(`a[data-cow-id="${cowId}"][data-action="show-less"]`);

        // Hide the full comments and show the short comments
        fullComments.style.display = "none";
        shortComments.style.display = "";

        // Hide the "Show Less" link and show the "Show More" link
        showLessLink.style.display = "none";
        showMoreLink.style.display = "";
    }


    const form = document.querySelector('#column-form');
    const table = document.querySelector('#cattle-table');
    const columns = Array.from(document.querySelectorAll('[name="columns"]'));

    // Show/hide columns based on user selection
    form.addEventListener('submit', (event) => {
      event.preventDefault();
      columns.forEach((column) => {
        const columnName = column.value;
        const columnCells = Array.from(table.querySelectorAll(`.cattle-${columnName}`));
        columnCells.forEach((cell) => {
          cell.style.display = column.checked ? '' : 'none';
        });
      });
    });
  </script>

{% endblock %}
{% endblock %}

my_farm/templates/cattle/confirmation_page.html
<!DOCTYPE html>
<html>
<head>
  <title>Confirmation Page</title>
</head>
<body>
  <h1>Row Deleted</h1>
  <p>The row has been successfully deleted.</p>
  <a href="{% url 'my_farm:cattle_info' %}">Back to Cattle Info</a>
</body>
</html>

my_farm/templates/cattle/search_cattle.html
{% extends 'base_user.html' %}
{% block content %}

<title>Cearch Cttle</title>

<body>

<p></p>

<form method="GET" action="{% url 'my_farm:search_cattle' %}">
    <input type="text" name="query" value="{{ query }}" placeholder="Search Cattle">
    <button type="submit">Search</button>
</form>


    <h3 style="text-align: center; margin: 20px;">-{{ query }}- search result</h3>



    <div class="table-responsive">
        <div class="table-container">
            <table class="table table-bordered">
        <thead>
            <tr class="column-names">
              <th>Type</th>
              <th>Number</th>
              <th>Name</th>
              <th>Gender</th>
              <th>Breed</th>
              <th>Birth date</th>
              <th>Acquisition method</th>
              <th>Entry date</th>
              <th>Loss method</th>
              <th>End date</th>
              <th>Comments</th>
            </tr>
          </thead>
        <tbody>
            {% for cattle in cattle_list %}
            <tr>
                <td>{{ cattle.type }}</td>
<td>
        <a href="{% url 'my_farm:cattle_detail' cattle.id %}">{{ cattle.number }}</a>
      </td>
                <td>{{ cattle.name }}</td>
                <td>{{ cattle.gender }}</td>
                <td>{{ cattle.breed }}</td>
                <td>{{ cattle.birth_date|date:"Y-m-d" }}</td>
                <td>{{ cattle.acquisition_method }}</td>
                <td>{{ cattle.entry_date|date:"Y-m-d" }}</td>
                <td>{{ cattle.loss_method }}</td>
                <td>{{ cattle.end_date|date:"Y-m-d" }}</td>
                <td>
                <div id="comments-short-{{ cow.id }}">{{ cattle.comments|truncatechars:5 }}</div>
                <div id="comments-full-{{ cow.id }}" style="display: none;">{{ cattle.comments }}</div>
                <small><a href="#" data-cattle-id="{{ cow.id }}" data-action="toggle-comments" onclick="toggleComments({{ cow.id }}); return false;" style="display: inline;">Show More</a></small>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No cattle found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
</body>

{% endblock %}

my_farm/templates/cattle/update_cattle.html
{% extends 'base_user.html' %}

{% block content %}

  <title>Update Cattle Information</title>

<body>
  <h3 class="text-uppercase" style="text-align: center; margin: 20px;">Update Cattle</h3>
  <div class="card-cattle">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.number.id_for_label }}" class="label-cattle">Number:</label>
        {{ form.number }}
      </div>
      <div class="form-group">
        <label for="{{ form.name.id_for_label }}" class="label-cattle">Name:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label for="{{ form.herd.id_for_label }}" class="label-cattle">Herd:</label>
        {{ form.herd }}
      </div>
      <div class="form-group">
        <label for="{{ form.gender.id_for_label }}" class="label-cattle">Gender:</label>
        {{ form.gender }}
      </div>
      <div class="form-group">
        <label for="{{ form.breed.id_for_label }}" class="label-cattle">Breed:</label>
        {{ form.breed }}
      </div>
      <div class="form-group">
        <label for="{{ form.birth_date.id_for_label }}" class="label-cattle">Birth Date:</label>
        {{ form.birth_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.acquisition_method.id_for_label }}" class="label-cattle">Acquisition Method:</label>
        {{ form.acquisition_method }}
      </div>
      <div class="form-group">
        <label for="{{ form.entry_date.id_for_label }}" class="label-cattle">Entry Date:</label>
        {{ form.entry_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.loss_method.id_for_label }}" class="label-cattle">Loss Method:</label>
        {{ form.loss_method }}
      </div>
      <div class="form-group">
        <label for="{{ form.end_date.id_for_label }}" class="label-cattle">End Date:</label>
        {{ form.end_date }}
      </div>
      <div class="form-group">
        <label for="{{ form.comments.id_for_label }}" class="label-cattle">Comments:</label>
        {{ form.comments }}
      </div>
      <div class="form-group">
        <label for="{{ form.picture.id_for_label }}" class="label-cattle">Picture:</label>
        {{ form.picture }}
      </div>

      <button type="submit" class="btn btn-custom">Update cattle information</button>
    </form>
  </div>

</body>

{% endblock %}