django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordResetView
from django_app.views import main, health_check
from user.views import profile, register, password
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='main'),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('my_farm/', include("my_farm.urls")),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('profile/', profile, name='profile'),
    path('profile/password_change/', password, name='password_change'),
    path('api/health/', health_check, name='health_check'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_farm/urls.py
from django.urls import path
from .views import home, group_data
from .views_herd import herd_list, add_herd, herd_detail, cattle_list_by_herd, search_herd, update_herd, \
    upload_herd_picture
from .views_movement_report import GenerateReportView, LivestockMovementReportView
from .views_field import field_list, field_detail, herd_list_by_field, update_field, add_field, upload_field_picture, \
    search_field
from .views_cattle import cattle_info, add_cattle, update_cattle, search_cattle, cattle_detail, \
    delete_confirmation_page, CattleDeleteView, upload_cattle_picture


app_name = "my_farm"

urlpatterns = [

    path('', home, name='home'),
    path('group_data/<slug:group_name>/', group_data, name='group_data'),

    path('generate_report/', GenerateReportView.as_view(), name='generate_report'),
    path('livestock_movement_report/', LivestockMovementReportView.as_view(), name='report'),

    path('cattle_info/', cattle_info, name='cattle_info'),
    path('cattle/<int:cattle_id>/', cattle_detail, name='cattle_detail'),
    path('add_cattle/', add_cattle, name='add_cattle'),
    path('update_cattle/<int:cattle_id>/', update_cattle, name='update_cattle'),
    path('upload_cattle_picture/<int:cattle_id>/', upload_cattle_picture, name='upload_cattle_picture'),
    path('cattle/delete/<int:pk>/', CattleDeleteView.as_view(), name='delete_cattle'),
    path('confirmation_page/', delete_confirmation_page, name='delete_confirmation_page'),
    path('search_cattle/', search_cattle, name='search_cattle'),

    path('herds/', herd_list, name='herd_list'),
    path('herds/<int:herd_id>/', herd_detail, name='herd_detail'),
    path('herds/new_herd', add_herd, name='add_herd'),
    path('herd/<int:herd_id>/cattle/', cattle_list_by_herd, name='cattle_list_by_herd'),
    path('herd/update_herd/<int:herd_id>/', update_herd, name='update_herd'),
    path('herd/upload_herd_picture/<int:herd_id>/', upload_herd_picture, name='upload_herd_picture'),
    path('search_herd/', search_herd, name='search_herd'),

    path('fields/', field_list, name='field_list'),
    path('fields/<int:field_id>/', field_detail, name='field_detail'),
    path('fields/new_field', add_field, name='add_field'),
    path('fields/<int:field_id>/herd/', herd_list_by_field, name='herd_list_by_field'),
    path('fields/update_field/<int:field_id>/', update_field, name='update_field'),
    path('fields/upload_field_picture/<int:field_id>/', upload_field_picture, name='upload_field_picture'),
    path('fields/search_field/', search_field, name='search_field')


]

my_farm/models.py
from django.db import models


class BaseModel(models.Model):
    """
    A base abstract model that provides a default manager and serves as a template for other models.
    """
    objects = models.Manager()

    class Meta:
        abstract = True


class CattleManager(models.Manager):
    """
    Custom manager for the Cattle model that filters out deleted cattle objects from the queryset.
    """

    def get_queryset(self):
        """
        Get the queryset for cattle objects with the 'deleted' field set to False.

        :return: A queryset containing cattle objects with 'deleted' set to False.
        """
        return super().get_queryset().filter(deleted=False)


class Cattle(models.Model):
    """
    Represents information about cattle, including breed, gender, acquisition method, and loss method.
    """

    BREED = [
        ('Angus', 'Angus'),
        ('Crossbreed', 'Crossbreed'),
    ]

    GENDER = [
        ('Heifer', 'Heifer'),
        ('Bull', 'Bull'),
        ('Cow', 'Cow'),
    ]

    ACQUISITION_METHOD = [
        ('Birth', 'Birth'),
        ('Purchase', 'Purchase'),
        ('Gift', 'Gift'),
    ]

    LOSS_METHOD = [
        ('Death', 'Death'),
        ('Sold', 'Sold'),
        ('Consumed', 'Consumed'),
        ('Gifted', 'Gifted'),
    ]

    type = models.CharField(default='Cattle', max_length=80, blank=False)
    number = models.CharField(max_length=80, blank=False, unique=True)
    name = models.CharField(max_length=80, blank=True, null=True)
    gender = models.CharField(choices=GENDER, max_length=80, blank=False)
    breed = models.CharField(choices=BREED, max_length=80, blank=False)
    birth_date = models.DateField(blank=True, null=True)
    acquisition_method = models.CharField(choices=ACQUISITION_METHOD, max_length=80, blank=True, null=True)
    entry_date = models.DateField(blank=True, null=True)
    herd = models.ForeignKey('Herd', on_delete=models.SET_NULL, blank=True, null=True)
    loss_method = models.CharField(choices=LOSS_METHOD, max_length=80, blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    comments = models.TextField(max_length=2000)
    deleted = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='cattle_pictures', blank=True, null=True)

    def delete(self):
        """
        Soft delete the cattle by setting the 'deleted' field to True and saving the object.
        """
        self.deleted = True
        self.save()

    class Meta:
        """
        Meta information for the Cattle model, including the human-readable names and default ordering.
        """
        verbose_name = "Cattle Info"
        verbose_name_plural = "Cattle Info"
        ordering = ['name']

    def __str__(self):
        """
        Returns a string representation of the cattle object, showing its name, gender, and birthdate.
        """
        return f'{self.name},  {self.gender}, {self.birth_date}'


class Field(models.Model):
    """
    Represents information about a field, including its name, location, and size.
    """
    SIZE_CHOICES = [
            ('ha', 'Ha'),
            ('ac', 'Ac'),
        ]

    name = models.CharField(max_length=80, blank=False)
    location = models.CharField(max_length=100, blank=False)
    coordinates = models.CharField(max_length=100, blank=False)
    field_size = models.FloatField(blank=True, null=True)
    size_unit = models.CharField(choices=SIZE_CHOICES, max_length=2, blank=True)
    field_type = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    description = models.TextField(max_length=1200, blank=True)
    picture = models.ImageField(upload_to='field_pictures', blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the field object, showing its name.
        """
        return self.name


class Herd(models.Model):
    """
    Represents information about a herd, including its name, location, and start date.
    """
    name = models.CharField(max_length=80, blank=False)
    location = models.CharField(max_length=100, blank=False)
    field = models.ForeignKey('Field', on_delete=models.SET_NULL, blank=True, null=True, related_name='field_herds')
    description = models.TextField(max_length=2000, blank=True)
    start_date = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    herd_leader = models.ForeignKey('Cattle', on_delete=models.SET_NULL, blank=True, null=True,
                                    related_name='herd_leader')
    picture = models.ImageField(upload_to='herd_pictures', blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the herd object, showing its name.
        """
        return self.name

my_farm/views.py
from datetime import date
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils import timezone
from .models import Herd, Field
from django.urls import reverse
from .cattle_groups import GroupsManagement, CattleGroupData


@login_required
def home(request):
    """
    Renders the home page of the "My Farm" application.

    Retrieves various statistics and groups of cattle for display on the home page.

    :param request: The HTTP request object.
    :return: The rendered home page with the required data.
    """
    active_herds_count = Herd.objects.filter(is_active=True, start_date__lte=timezone.now()).count()
    active_field_count = Field.objects.filter(is_active=True).count()

    groups_manager = GroupsManagement()
    today_groups = groups_manager.calculate_groups(estimation_date=date.today())

    total_cattle_count = 0
    for group_data in today_groups.values():
        alive_cows_in_group = 0
        for cattle_data in group_data:
            if cattle_data['cattle']['end_date'] is None:
                alive_cows_in_group += 1
        total_cattle_count += alive_cows_in_group

    groups = []
    for group_name, cattle_data in today_groups.items():
        group = CattleGroupData(group_name, cattle_data)
        group.count_active_cattle()
        group_url = reverse('my_farm:group_data', args=[slugify(group_name)])
        group.url = group_url
        groups.append(group)

    context = {
        'groups': groups,
        'active_herds_count': active_herds_count,
        'active_field_count': active_field_count,
        'total_cattle_count': total_cattle_count,
    }

    return render(request, 'my_farm/my_farm_main.html', context)


def group_data(request, group_name):
    """
    Renders the group data page for the selected group.

    Retrieves the cattle data for the selected group and displays it on the page.

    :param request: The HTTP request object.
    :param group_name: The name of the selected group.
    :return: The rendered group data page with the selected group's data.
    """
    groups_manager = GroupsManagement()
    today_cattle = groups_manager.calculate_groups(estimation_date=date.today())

    selected_group = group_name

    groups = []
    if selected_group in today_cattle:
        cattle_data = today_cattle[selected_group]
        group = CattleGroupData(selected_group, cattle_data)
        group.cattle_data()
        groups.append(group)

    context = {
        'groups': groups,
        'selected_group': selected_group
    }
    return render(request, 'my_farm/group_data.html', context)

my_farm/templates/herd/add_herd.html
{% extends 'base_user.html' %}

{% block content %}
    <title>Add Herd Information</title>

    <h3 class="text-uppercase" style="text-align: center; margin: 20px;">Add Herd</h3>
    <div class="card-herds">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}" class="label-herd">Name:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.location.id_for_label }}" class="label-herd">Location:</label>
                {{ form.location }}
            </div>
            <div class="form-group">
                <label for="{{ form.field.id_for_label }}" class="label-herd">Field:</label>
                {{ form.field }}
            </div>
            <div class="form-group">
                <label for="{{ form.cattle.id_for_label }}" class="label-herd">Cattle:</label>
                <select class="form-control select2-multiple" id="{{ form.cattle.id_for_label }}"
                        name="{{ form.cattle.name }}" multiple>
                    {% for option in cattle_queryset %}
                        <option value="{{ option.pk }}">{{ option }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}" class="label-herd">Description:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="{{ form.start_date.id_for_label }}" class="label-herd">Start Date:</label>
                {{ form.start_date }}
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" id="{{ form.is_active.id_for_label }}"
                       name="{{ form.is_active.name }}" {% if form.is_active.value %}checked{% endif %}>
                <label class="form-check-label label-herd" for="{{ form.is_active.id_for_label }}">Is Active</label>
            </div>
<div class="form-group">
    <label for="{{ form.herd_leader.id_for_label }}" class="label-herd">Herd Leader:</label>
    <select class="form-control" id="{{ form.herd_leader.id_for_label }}" name="{{ form.herd_leader.name }}">
        <option value="" {% if not form.herd_leader.value %}selected{% endif %}>None</option>
        {% for option in cattle_queryset %}  {# Correct the queryset variable here #}
            <option value="{{ option.pk }}" {% if form.herd_leader.value == option.pk %}selected{% endif %}>{{ option }}</option>
        {% endfor %}
    </select>
</div>
            <div class="form-group">
                <label for="{{ form.picture.id_for_label }}" class="label-herd">Picture:</label>
                {{ form.picture }}
            </div>
            <button type="submit" class="btn btn-custom" style="background-color: #b5a369;">Add herd information
            </button>
        </form>
    </div>
{% endblock %}

my_farm/templates/herd/cattle_list_by_herd.html
{% extends 'base_user.html' %}
{% block content %}

<title>Cattle in the Herd</title>


<h3 class="text-uppercase" style="text-align: center; margin: 30px;">
    Cattle in - <a style="color:blue;" href="{% url 'my_farm:herd_detail' herd.id %}">{{ herd.name }}</a> - herd
</h3>

<table class="table table-bordered">
  <thead>
    <tr class="column-names-herds">
      <th>Number</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Entry Date</th>
      <th>Breed</th>
      <th>Loss method</th>
      <th>Comments</th>
    </tr>
  </thead>
  <tbody>
    {% for cattle in cattle_list %}
    <tr>
      <td>
        <a href="{% url 'my_farm:cattle_detail' cattle.id %}">{{ cattle.number }}</a>
      </td>
      <td>{{ cattle.name }}</td>
      <td>{{ cattle.gender }}</td>
      <td>{{ cattle.entry_date|date:"Y-m-d" }}</td>
      <td>{{ cattle.breed }}</td>
      <td>{{ cattle.loss_method }}</td>
      <td>
        <div id="comments-short-{{ cattle.id }}">{{ cattle.comments|truncatechars:5 }}</div>
        <div id="comments-full-{{ cattle.id }}" style="display: none;">{{ cattle.comments }}</div>
        <small><a href="#" data-cattle-id="{{ cattle.id }}" data-action="toggle-comments" onclick="toggleComments({{ cattle.id }}); return false;" style="display: inline;">Show More</a></small>
      </td>
    </tr>
    {% empty %}
            <tr>
                <td colspan="3">No cattle in the herd.</td>
            </tr>
            {% endfor %}
  </tbody>
</table>
</div>


{% endblock %}

my_farm/templates/herd/herd_detail.html
{% extends 'base_user.html' %}

{% block content %}

<title>Herd Detail</title>

{% if herd %}
<h4 style="text-align: center; margin: 20px; font-weight: bold;">{{ herd.name }}</h4>

<table class="table table-bordered" style="max-width: 500px; margin-left: auto; margin-right: auto;">
    <tr>
        <th class="herd-detail">Picture</th>
        <td style="width: 300px; height: 200px; max-width: 100%; max-height: 100%;">
            {% if herd.picture %}
            <img src="{{ herd.picture.url }}" style="max-width: 100%; max-height: 100%;">
            {% else %}
            No picture available.
            {% endif %}
        </td>
    </tr>
    <tr>
        <th class="herd-detail">Name</th>
        <td>{{ herd.name }}</td>
    </tr>
    <tr>
        <th class="herd-detail">Location</th>
        <td>{{ herd.location }}</td>
    </tr>
    <tr>
        <th class="herd-detail">Field</th>
         <td>
                    {% if herd.field %}
                        <a href="{% url 'my_farm:field_detail' herd.field.id %}">{{ herd.field }}</a>
                    {% else %}
                        No field.
                    {% endif %}
                </td>
    </tr>
    <tr>
        <th class="herd-detail">Description</th>
        <td>{{ herd.description }}</td>
    </tr>
    <tr>
        <th class="herd-detail">Start Date</th>
        <td>{{ herd.start_date|date:"Y-m-d" }}</td>
    </tr>
    <tr>
        <th class="herd-detail">Active</th>
        <td>{{ herd.is_active }}</td>
    </tr>
    <tr>
        <th class="herd-detail">Herd Leader</th>
        <td>{{ herd.herd_leader }}</td>
    </tr>
    <tr>
        <th class="herd-detail">Cattle</th>
        <td>
            <a href="{% url 'my_farm:cattle_list_by_herd' herd.id %}">{{ herd.cattle_count }}</a>
        </td>
    </tr>
    <tr>
        <th class="herd-detail">Update</th>
        <td>
            <!-- Update link -->
            <a href="{% url 'my_farm:update_herd' herd.id %}">Update</a>
        </td>
    </tr>
</table>

{% else %}
<p>No cattle selected.</p>
{% endif %}
{% endblock %}

my_farm/templates/herd/herd_list.html
{% extends 'base_user.html' %}

{% block content %}
  <title>Herds</title>

  <h3 class="text-uppercase" style="text-align: center; margin: 20px;">My Herds</h3>

  <!-- Search Tool -->
  <form method="GET" action="{% url 'my_farm:search_herd' %}" style="margin-top: 20px;">
    <input type="text" name="query" placeholder="Search in Herds">
    <button type="submit">Search</button>
  </form>

  <form method="POST" action="{% url 'my_farm:add_herd' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-custom">New Herd</button>
  </form>

  <p></p>

  <div class="table-responsive">
    <table id="herd-table" class="table table-bordered">
      <thead>
        <tr class="column-names-herds">
          <th>Name</th>
          <th>Active</th>
          <th>Field</th>
          <th>Start Date</th>
          <th>Herd Leader</th>
          <th>Number of Cattle</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for herd in page_obj %}
          <tr>
            <td>
              <a href="{% url 'my_farm:herd_detail' herd.id %}">{{ herd.name }}</a>
            </td>
            <td>{{ herd.is_active }}</td>
            <td>
              {% if herd.field %}
                <a href="{% url 'my_farm:field_detail' herd.field.id %}">{{ herd.field }}</a>
              {% else %}
                No field.
              {% endif %}
            </td>
            <td>{{ herd.start_date|date:"Y-m-d" }}</td>
            <td>{{ herd.herd_leader }}</td>
            <td>
              <a href="{% url 'my_farm:cattle_list_by_herd' herd.id %}">{{ herd.count_cattle }}</a>
            </td>
            <td>
              <div id="comments-short-{{ herd.id }}">{{ herd.description|truncatechars:5 }}</div>
              <div id="comments-full-{{ herd.id }}" style="display: none;">{{ herd.description }}</div>
              <small>
                <a href="#" data-cattle-id="{{ herd.id }}" data-action="toggle-comments" onclick="toggleComments({{ herd.id }}); return false;" style="display: inline;">Show More</a>
              </small>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% if page_obj.has_other_pages %}
<div class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <a href="?page=1" class="page-link">&laquo; First</a>
  <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&lsaquo; Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
  <a href="?page={{ num }}" class="page-link active">{{ num }}</a>
  {% else %}
  <a href="?page={{ num }}" class="page-link">{{ num }}</a>
  {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next &rsaquo;</a>
  <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Last &raquo;</a>
  {%endif %}
</div>

{% endif %}



{% endblock %}

my_farm/templates/herd/search_herd.html
{% extends 'base_user.html' %}
{% block content %}

<title>Search Herd</title>

<body>

<p></p>

<form method="GET" action="{% url 'my_farm:search_herd' %}">
    <input type="text" name="query" value="{{ query }}" placeholder="Search Cattle">
    <button type="submit">Search</button>
</form>


    <h3 style="text-align: center; margin: 20px; color: #b5a369;">-{{ query }}- search result</h3>



    <div class="table-responsive">
        <div class="table-container">
<table id="herd-table" class="table table-bordered">
  <thead>
    <tr class="column-names-herds">
              <th class="cattle-name">Name</th>
              <th class="cattle-entry_date">Active</th>
              <th class="cattle-breed">Field</th>
              <th class="cattle-acquisition_method">Start Date</th>
              <th class="cattle-loss_method">Herd Leader</th>
              <th class="cattle-end_date">Number of Cattle</th>
              <th class="cattle-birth_date">Description</th>
            </tr>
          </thead>
        <tbody>
            {% for herd in herd_list %}
            <tr>
                <td>
                <a href="{% url 'my_farm:herd_detail' herd.id %}">{{ herd.name }}</a>
                </td>
                <td>{{ herd.is_active }}</td>
                <td>
              {% if herd.field %}
                <a href="{% url 'my_farm:field_detail' herd.field.id %}">{{ herd.field }}</a>
              {% else %}
                No field.
              {% endif %}
                </td>
                <td>{{ herd.start_date|date:"Y-m-d" }}</td>
                <td>{{ herd.herd_leader }}</td>
                <td>
                <a href="{% url 'my_farm:cattle_list_by_herd' herd.id %}">{{ herd.count_cattle }}</a>
                </td>
                 <td>
                <div id="comments-short-{{ herd.id }}">{{ herd.description|truncatechars:5 }}</div>
                <div id="comments-full-{{ herd.id }}" style="display: none;">{{ herd.description }}</div>
              <small><a href="#" data-cattle-id="{{ herd.id }}" data-action="toggle-comments" onclick="toggleComments({{ herd.id }}); return false;" style="display: inline;">Show More</a></small>
                </td>
            </tr>

            {% empty %}
            <tr>
                <td colspan="3">No herd found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
</body>

{% endblock %}

my_farm/templates/herd/update_herd.html
{% extends 'base_user.html' %}

{% block content %}
    <title>Update Herd Information</title>

    <h3 class="text-uppercase" style="text-align: center; margin: 20px;">Update -{{ herd.name }}- Herd</h3>
    <div class="card-herds">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}" class="label-herd">Name:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.location.id_for_label }}" class="label-herd">Location:</label>
                {{ form.location }}
            </div>
            <div class="form-group">
                <label for="{{ form.field.id_for_label }}" class="label-herd">Field:</label>
                {{ form.field }}
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}" class="label-herd">Description:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="{{ form.start_date.id_for_label }}" class="label-herd">Start Date:</label>
                {{ form.start_date }}
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" id="{{ form.is_active.id_for_label }}"
                       name="{{ form.is_active.name }}" {% if form.is_active.value %}checked{% endif %}>
                <label class="form-check-label label-herd" for="{{ form.is_active.id_for_label }}">Is Active</label>
            </div>
            <div class="form-group">
    <label for="{{ form.herd_leader.id_for_label }}" class="label-herd">Herd Leader:</label>
    <select class="form-control" id="{{ form.herd_leader.id_for_label }}" name="{{ form.herd_leader.name }}">
        <option value="">None</option>
        {% for option in form.fields.herd_leader.queryset %}
            <option value="{{ option.pk }}" {% if option.pk == form.herd_leader.value.pk %}selected{% endif %}>{{ option }}</option>
        {% endfor %}
    </select>
</div>
            <div class="form-group">
                <label for="{{ form.picture.id_for_label }}" class="label-herd">Picture:</label>
                {{ form.picture }}
            </div>
            <button type="submit" class="btn btn-custom" style="background-color: #b5a369;">Update herd information</button>
        </form>
    </div>
{% endblock %}